version: "3"

services:

  #db:
  #  image: camilomolina/hsqldb:2.3.4
  #  ports:
  #  - "9001:9001"
  #  volumes:
  #  - hsqldb-data:/var/lib/hsqldb/data
  # restart: always
  db:
    image: mysql:5.7.17
    ports:
    - "3306:3306"
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
    - MYSQL_PASSWORD=11042.
    - MYSQL_USER=root
    restart: always

  user:
    build: user/target/docker
    ports:
    - "8010:8080"
    - "8710:8787"
    depends_on:
    - db

  team:
    build: team/target/docker
    ports:
    - "8011:8080"
    - "8711:8787"
    depends_on:
    - db

  competitive:
    build: competitive/target/docker
    ports:
    - "8012:8080"
    - "8712:8787"
    depends_on:
    - db


volumes:
  hsqldb-data:
    external: false

  mysql-data:
    external: false

